
#
# Copyright (C) 2020 Nate Ding
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_Title:=LuCI Extended Support for dnsmasq
LUCI_PKGARCH=all

PKG_VERSION:=1.0
PKG_RELEASE:=20210627

PKG_MAINTANINER:=sepo83
PKG_LICENSE:=GLPv3
PKG_LICENSE_FILES:=LICENSE

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
